### ISSUE TITLE
Unable to edit three sections of the home page.

### ISSUE THREAD

**Issue by Mobashir-Monim** [jubaedprince/onnesha#2]
Currently unable to edit the top part of the home page; which includes all the information in the top, above the main navigation menu; and the bottom part, after the "Information for teachers and students, parenting information and education news", in addition to that, the pictures in the collage right after signature is also having the same problem.

**Comment by jubaedprince** [comment]
the pictures in the picture collage right after signature is also has the same problem : https://youtu.be/VnJdhNopniQ

**Comment by jubaedprince** [comment]
To change logo at the top:
Theme Options>Header>Header
To change other stuffs at top beside logo:
Layout Blocks>Top Bar
To change other stuffs at the footer:
Layout Blocks>Footer
